server:
  port: 8011
  servlet:
    context-path: /cavy
spring:
#  dynamic:
#    primary: mysql #设置默认的数据源或者数据源组,默认值即为master
#    datasource:
#      mysql:
#        url: jdbc:mysql://${mysql.host:localhost}:${mysql.port:3306}/${mysql.db:cavy}?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
#        username: ${mysql.username:root}
#        password: ${mysql.password:123456}
#        driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#      pgsql:
#        url: jdbc:jdbc:postgresql://localhost:5432/cavy
#        username: postgres
#        password: 123456
#        driver-class-name: org.postgresql.Driver
#      slave_2:
#        url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#        username: ENC(xxxxx)
#        password: ENC(xxxxx)
#        driver-class-name: com.mysql.jdbc.Driver
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./${spring.application.name}
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: sa
    password: sa
    continue-on-error: true
    initialization-mode: never
    platform: h2
  h2:
    #开启console 访问 默认false
    console:
      enabled: true
      settings:
        #开启h2 console 跟踪 方便调试  默认 false
        trace: true
        #允许console 远程访问 默认false
        web-allow-others: false
        #h2 访问路径上下文
      path: /h2-console

  #    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${mysql_host:localhost}:${mysql_port:3306}/${mysql_db:cavy}?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=false
#    username: ${mysql_username:root}
#    password: ${mysql_password:123456}
  #    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driverClassName: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 123456
#      url: jdbc:mysql://localhost:3307/cavy?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      validationQuery: select 1
#      validationQueryTimeout: 5
#      testOnBorrow: false
#      testOnReturn: false
#      testWhileIdle: true
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      # 合并多个DruidDataSource的监控数据
#      useGlobalDataSourceStat: true
#      filters: stat
#      webStatFilter:
#        enabled: true
#        urlPattern: /api/*
#        sessionStatEnable: true
#        sessionStatMaxCount: 1000
#        profileEnable: true
#      statViewServlet:
#        enabled: true
#        urlPattern: /druid/*
#        resetEnable: false
#        loginUsername: admin
#        loginPassword: admin
#      filter:
#        stat:
#          enabled: true
#          mergeSql: true
#        commons-log:
#          connection-logger-name: stat,wall,log4j

  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}
    username: guest
    password: guest
    virtualHost: /
    #开启发送失败返回
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      #开启ack
      direct:
        acknowledge-mode: manual
  redis:
    database: 0
    host: ${redis_host:127.0.0.1}
    port: ${redis_port:6379}
    password: 123456
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  jackson:
      date-format: 'yyyy-MM-dd HH:mm:ss'
      time-zone: 'GMT+8'
      serialization.write-dates-as-timestamps: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: cavy-backend
es:
  address: ${es_address:localhost:9200}
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.jh.cavymanage.domain
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.data.convert.CustomConversions: ERROR
    o.s.boot.actuate.endpoint.EndpointId: ERROR
   # com.jh.cavy.common.Result.ResponseControllerAdvice: debug
  file:
    path: logs
nacos:
  enable: false
cavy:
  init-database: cavy
  init-file: init
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: shutdown
cache:
  use: caffeineHandle
message:
  enable: true
file:
  type: none
#  type: minio
minio:
  endpoint: ${minio_endpoint:"http://localhost:9000/"}
  port: ${minio_port:9000}
  accessKey: Mingmei
  secretKey: Mingmei/K7MDENG/bPxRfiCYEXAMPLEKEY
  secure: false
  bucketName: "images"
  configDir: "/root/data"
  webUrl: ${minio_weburl:"http://localhost:9000/"}