INSERT INTO t_bus_answer (question_id, content, add_user, add_time, update_user, update_time) VALUES (1, '哈哈1', 'admin', '2021-01-01 00:00:00', null, null);
INSERT INTO t_bus_answer (question_id, content, add_user, add_time, update_user, update_time) VALUES (1, '哈哈2', 'admin', '2021-01-01 00:00:00', null, null);
INSERT INTO t_bus_answer (question_id, content, add_user, add_time, update_user, update_time) VALUES (1, '哈哈3', 'admin', '2021-01-01 00:00:00', null, null);
INSERT INTO t_bus_answer (question_id, content, add_user, add_time, update_user, update_time) VALUES (1, '哈哈4', 'admin', '2021-01-01 00:00:00', null, null);
INSERT INTO t_bus_answer (question_id, content, add_user, add_time, update_user, update_time) VALUES (1, '哈哈5', 'admin', '2021-01-01 00:00:00', null, null);
INSERT INTO t_bus_answer (question_id, content, add_user, add_time, update_user, update_time) VALUES (1, '哈哈6', 'admin', '2021-01-01 00:00:00', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('test', 'test', null, null, null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('test', 'test', null, null, null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('test', 'test', null, null, null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('test', 'test', null, null, null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('test', 'test', null, null, null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('', null, null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('', null, null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('123', '<p>123</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('11', '<p>11</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('123', '<p>123</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('123', '<p>123</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('3', '<p>3</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('2', '<p>2</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('2', '<p>2</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('4', '<p>4</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('2', '<p>2</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('2', '<p>2</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('22', '<p>22</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('123', '<p>123</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('2', '<p>2</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('123', '<p>123</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('44', '<p>44</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, null, null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', null, 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', '2021-07-31 14:53:48', 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('123', '<p>123</p>', '2021-07-31 15:08:21', 'admin', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('3', '<p>3</p>', '2021-08-01 09:49:45', '123', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('1', '<p>1</p>', '2021-08-06 15:15:10', '123', null, null);
INSERT INTO t_bus_question (title, content, add_time, add_user, update_time, update_user) VALUES ('.', '<p>.0</p>', '2021-08-06 15:24:36', '123', null, null);
INSERT INTO t_sys_config (code, code_value, name, add_time, add_user, update_time, update_user) VALUES ('init-database', 'cavy', '初始化数据库名称', null, null, null, null);
INSERT INTO t_sys_file (file_code, file_name, file_path, web_url, add_user, add_time, update_user, update_time) VALUES ('022a0c0c18505a1290081bfc06cf45af152261ab972b27a7f46d79b828169480', '15358071_large.png', '2021/31/31/15358071_large.png', 'http://193.149.161.195:9000/2021/31/31/15358071_large.png', null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (4, 'knowledge', '知识管理', 0, 'el-icon-reading', 'knowledge', 1, 4, 4, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (1, 'main', '后台中心', 0, 'el-icon-house', 'main', 1, 1, 1, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (2, 'order', '订单列表', 0, 'el-icon-s-order', 'order', 1, 6, 5, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (4, 'article', '文章管理', 10, 'el-icon-tickets', 'knowledge/article', 1, null, 1, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (8, 'category', '分类管理', 10, 'el-icon-menu', 'knowledge/category', 1, 2, 2, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (16, 'user', '用户管理', 22, 'el-icon-user-solid', 'power/user', 1, 2, 1, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (32, 'test2', '消息管理', 0, 'el-icon-message', 'message/websocket', 1, 5, 6, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (64, 'test-3', '消息推送', 16, 'el-icon-chat-dot-square', 'message/websocket', 1, null, 1, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (128, 'system', '系统管理', 0, 'el-icon-setting', 'system', 1, 2, 2, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (256, 'file', '文件管理', 18, 'el-icon-file', 'system/file', 1, 9, 1, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (512, 'questionanswer', '问答管理', 0, 'el-icon-question', 'questionanswer', 1, 7, 7, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (4, 'label', '标签管理', 10, 'el-icon-collection-tag', 'knowledge/label', 1, 1, 3, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (16, 'power', '权限管理', 0, 'el-icon-s-cooperation', 'power/power', 1, 3, 3, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (16, 'menu', '菜单管理', 22, 'el-icon-s-operation', 'power/menu', 1, 2, 2, 1, null, null, null, null);
INSERT INTO t_sys_menu (menu_id, menu_code, menu_name, parent_id, icon, url, hidden, weight, sort, is_default, add_time, add_user, update_time, update_user) VALUES (16, 'role', '角色管理', 22, 'el-icon-files', 'power/role', 1, 3, 3, 1, null, null, null, null);
INSERT INTO t_sys_role (role_name, add_time, add_user, update_time, update_user) VALUES ('测试用户', null, null, null, null);
INSERT INTO t_sys_user (user_name, pwd, real_name, gender, phone, email, add_time, add_user, update_time, update_user) VALUES ('admin', ' 123', '超级管理员', 1, '110', 'admin@qq.com', '2021-07-05 14:55:38', 'admin', null, null);
INSERT INTO t_sys_user (user_name, pwd, real_name, gender, phone, email, add_time, add_user, update_time, update_user) VALUES ('guest', ' guest', '游客', 1, '110', 'admin@qq.com', '2021-07-05 14:55:38', 'admin', null, null);
INSERT INTO t_sys_user (user_name, pwd, real_name, gender, phone, email, add_time, add_user, update_time, update_user) VALUES ('123', ' guest', 'test', 1, '110', 'admin@qq.com', '2021-07-05 14:55:38', 'admin', null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 1, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 2, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 3, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 4, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 5, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 6, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 7, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 8, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 9, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 10, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 11, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 12, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 13, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 14, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 1, 15, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 10, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 11, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 12, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 13, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 14, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 15, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 16, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 17, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 18, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 19, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 20, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 21, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 22, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 23, null, null, null, null);
INSERT INTO t_sys_user_menu (id, user_id, menu_id, add_time, add_user, update_time, update_user) VALUES (null, 2, 24, null, null, null, null);
INSERT INTO t_sys_user_role (id, user_id, role_id) VALUES (1, 3, 1);
